In [9]:
# Import Dependencies
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
%matplotlib notebook

In [10]:
# Import "Owners Assistance" spreadsheet
owner_assist = './data/FEMA_Housing_Assistance_Owners.csv'
OA_df = pd.read_csv(owner_assist, low_memory=False, thousands = ',')
OAt_df = OA_df.sort_values(["Disaster", "Zip Code"])
OAt_df

# Only include inputs that can be summed or are part of the grouping
OAt_df["Disaster"] = OAt_df["Disaster"].astype(str)
OAt_df["address"] = OAt_df["Disaster"] + ', ' + OAt_df["State"] + ', ' + OAt_df["County"]


OAt_df = OAt_df.loc[:,["address", "Approved for FEMA Assistance",
               "Approved between $1 and $10,000", "Approved between $10,001 and $25,000", 
               "Approved between $25,001 and Max", "Total Approved IHP Amount"]]
OAt_df = OAt_df.dropna(how='any')


OAt_df['Approved for FEMA Assistance'] = OAt_df['Approved for FEMA Assistance'].str.replace(',','').str.replace('$','').astype('int')
OAt_df['Approved between $1 and $10,000'] = OAt_df['Approved between $1 and $10,000'].str.replace(',','').str.replace('$','').astype('int')
OAt_df['Approved between $10,001 and $25,000'] = OAt_df['Approved between $10,001 and $25,000'].str.replace(',','').str.replace('$','').astype('int')
OAt_df['Approved between $25,001 and Max'] = OAt_df['Approved between $25,001 and Max'].str.replace(',','').str.replace('$','').astype('int')
OAt_df['Total Approved IHP Amount'] = OAt_df['Total Approved IHP Amount'].str.replace(',','').str.replace('$','').astype('float')
print(OAt_df.dtypes)

OAt_df

address                                  object
Approved for FEMA Assistance              int32
Approved between $1 and $10,000           int32
Approved between $10,001 and $25,000      int32
Approved between $25,001 and Max          int32
Total Approved IHP Amount               float64
dtype: object

,address,Approved for FEMA Assistance,"Approved between $1 and $10,000","Approved between $10,001 and $25,000","Approved between $25,001 and Max",Total Approved IHP Amount
25394,"4116, IL, Cook (County)",0,0,0,0,0.0
25678,"4116, IL, Lake (County)",30,30,0,0,81328.0
25276,"4116, IL, Cook (County)",15,15,0,0,33529.0
25277,"4116, IL, Cook (County)",4,4,0,0,5889.0
25369,"4116, IL, Cook (County)",4,3,1,0,17365.0
...,...,...,...,...,...,...
26986,"4466, TX, Jefferson (County)",7,7,0,0,15725.0
26987,"4466, TX, Jefferson (County)",127,105,21,1,654432.0
26988,"4466, TX, Jefferson (County)",6,5,1,0,24691.0
26990,"4466, TX, Jefferson (County)",0,0,0,0,0.0
26999,"4466, TX, Jefferson (County)",0,0,0,0,0.0

In [3]:
# Sum up the data for Renters Assistance
OAg_gb = OAt_df.groupby(["address"])

OAg_df = OAg_gb.sum()
OAg_df

,Approved for FEMA Assistance,"Approved between $1 and $10,000","Approved between $10,001 and $25,000","Approved between $25,001 and Max",Total Approved IHP Amount
address,,,,,
"4116, IL, Brown (County)",8,6,2,0,32272.0
"4116, IL, Bureau (County)",260,251,9,0,622024.0
"4116, IL, Calhoun (County)",14,14,0,0,31821.0
"4116, IL, Clark (County)",11,9,2,0,44331.0
"4116, IL, Cook (County)",36895,35846,966,83,90293298.0
...,...,...,...,...,...
"4466, TX, Jefferson (County)",2319,1436,842,41,18405207.0
"4466, TX, Liberty (County)",579,435,137,7,3696788.0
"4466, TX, Montgomery (County)",1100,780,293,27,8022615.0
"4466, TX, Orange (County)",1585,1186,374,25,9672865.0
"4466, TX, San Jacinto (County)",20,18,2,0,82351.0

In [4]:
# Import "Renters Assistance" spreadsheet
renter_assist = './data/FEMA_Housing_Assistance_Renters.csv'
RA_df = pd.read_csv(renter_assist, low_memory=False, thousands = ',')
RAt_df = RA_df.sort_values(["Disaster", "Zip Code"])
RAt_df

# Only include inputs that can be summed or are part of the grouping
RAt_df["Disaster"] = RAt_df["Disaster"].astype(str)
RAt_df["address"] = RAt_df["Disaster"] + ', ' + RAt_df["State"] + ', ' + RAt_df["County"]

# Only include inputs that can be summed or are part of the grouping

RAt_df = RAt_df.loc[:,["address", "Approved for FEMA Assistance",
                "Total with Moderate Damage", "Total with Major Damage", 
                 "Total with Substantial Damage", "Total Approved IHP Amount"]]
RAt_df = RAt_df.dropna(how='any')
RAt_df['Total Approved IHP Amount'] = RAt_df['Total Approved IHP Amount'].str.replace(',','').str.replace('$','').astype('float')
print(RAt_df.dtypes)

RAt_df

address                           object
Approved for FEMA Assistance       int64
Total with Moderate Damage         int64
Total with Major Damage            int64
Total with Substantial Damage      int64
Total Approved IHP Amount        float64
dtype: object

,address,Approved for FEMA Assistance,Total with Moderate Damage,Total with Major Damage,Total with Substantial Damage,Total Approved IHP Amount
20426,"4116, IL, Lake (County)",4,4,0,0,11231.0
20122,"4116, IL, Cook (County)",0,0,0,0,0.0
20123,"4116, IL, Cook (County)",1,0,0,0,260.0
20206,"4116, IL, Cook (County)",2,1,0,0,3619.0
20284,"4116, IL, Cook (County)",1,0,0,0,2590.0
...,...,...,...,...,...,...
21400,"4466, TX, Jefferson (County)",40,32,0,0,62725.0
21401,"4466, TX, Jefferson (County)",181,178,0,0,568172.0
21402,"4466, TX, Jefferson (County)",11,2,0,0,19588.0
21245,"4466, TX, Harris (County)",0,0,0,0,0.0
21403,"4466, TX, Jefferson (County)",28,17,1,0,60184.0

In [5]:
# Sum up the data for Renters Assistance
RAg_gb = RAt_df.groupby(["address"])

RAg_df = RAg_gb.sum()
Rag_df = RAg_df.sort_values("address")
RAg_df

,Approved for FEMA Assistance,Total with Moderate Damage,Total with Major Damage,Total with Substantial Damage,Total Approved IHP Amount
address,,,,,
"4116, IL, Bureau (County)",19,9,1,4,29177.0
"4116, IL, Calhoun (County)",4,4,0,0,7079.0
"4116, IL, Clark (County)",0,0,0,0,0.0
"4116, IL, Cook (County)",12965,6996,223,1990,37099655.0
"4116, IL, Crawford (County)",1,1,0,0,2079.0
...,...,...,...,...,...
"4466, TX, Jefferson (County)",1207,1050,14,0,3933428.0
"4466, TX, Liberty (County)",184,152,0,0,566726.0
"4466, TX, Montgomery (County)",207,169,22,0,813403.0
"4466, TX, Orange (County)",322,291,1,0,1039349.0
"4466, TX, San Jacinto (County)",3,2,0,0,4214.0

In [6]:
# Import "Disaster Declarations" spreadsheet
disaster_declare = './data/DisasterDeclarationsSummaries.csv'
DD_df = pd.read_csv(disaster_declare, low_memory=False)

# Only include disasters that are in the FEMA assistance files
DDt_df = DD_df.loc[(DD_df ["disasterNumber"]>=4116), :]
DDt_df = DDt_df.loc[(DDt_df ["disasterNumber"]<=4466), :] 

# Only include inputs that can be summed or are part of the grouping
DDt_df["disasterNumber"] = DDt_df["disasterNumber"].astype(str)
DDt_df["address"] = DDt_df["disasterNumber"] + ', ' + DDt_df["state"] + ', ' + DDt_df["designatedArea"]

# Only take the columns that could provide some use to us
DDt_df = DDt_df.loc[:,["address", "fipsStateCode", 
                       "fipsCountyCode", "placeCode", "fyDeclared", 
                       "incidentType", "incidentBeginDate", "incidentEndDate"]]

# Sort the dataframe by the disaster Numbers
DDt_df = DDt_df.sort_values("address")
DDt_df
# Note the minimum and maximum disaster Numbers

,address,fipsStateCode,fipsCountyCode,placeCode,fyDeclared,incidentType,incidentBeginDate,incidentEndDate
44656,"4116, IL, Adams (County)",17,1,99001,2013,Flood,2013-04-16T13:37:00.000Z,2013-05-05T04:00:00.000Z
44721,"4116, IL, Brown (County)",17,9,99009,2013,Flood,2013-04-16T13:37:00.000Z,2013-05-05T04:00:00.000Z
44692,"4116, IL, Bureau (County)",17,11,99011,2013,Flood,2013-04-16T13:37:00.000Z,2013-05-05T04:00:00.000Z
44685,"4116, IL, Calhoun (County)",17,13,99013,2013,Flood,2013-04-16T13:37:00.000Z,2013-05-05T04:00:00.000Z
44658,"4116, IL, Carroll (County)",17,15,99015,2013,Flood,2013-04-16T13:37:00.000Z,2013-05-05T04:00:00.000Z
...,...,...,...,...,...,...,...,...
50994,"4466, TX, Liberty (County)",48,291,99291,2020,Flood,2019-09-17T12:00:00.000Z,2019-09-23T12:00:00.000Z
50993,"4466, TX, Montgomery (County)",48,339,99339,2020,Flood,2019-09-17T12:00:00.000Z,2019-09-23T12:00:00.000Z
50990,"4466, TX, Orange (County)",48,361,99361,2020,Flood,2019-09-17T12:00:00.000Z,2019-09-23T12:00:00.000Z
51045,"4466, TX, San Jacinto (County)",48,407,99407,2020,Flood,2019-09-17T12:00:00.000Z,2019-09-23T12:00:00.000Z
50988,"4466, TX, Statewide",48,0,0,2020,Flood,2019-09-17T12:00:00.000Z,2019-09-23T12:00:00.000Z