In [1]:
import pandas as pd
import numpy as np
import json
import requests
import xmltodict, json

In [2]:
url1 ="https://www.zillow.com/webservice/GetUpdatedPropertyDetails.htm?zws-id=X1-ZWz17giky9jf9n_43hp8&zpid=48749425"
url2 ="http://www.zillow.com/webservice/GetDeepComps.htm?zws-id=X1-ZWz17giky9jf9n_43hp8&zpid=48749425&count=5"
url3 ="http://www.zillow.com/webservice/GetDeepSearchResults.htm?zws-id=X1-ZWz17giky9jf9n_43hp8&address=2114+Bigelow+Ave&citystatezip=Seattle%2C+WA"

In [12]:
#Request API
response1 = requests.get(url1).content
response2 = requests.get(url2)
response3 = requests.get(url3)

In [5]:
#print XML Response
#real = response1
print(response1)

b'<?xml version="1.0" encoding="utf-8"?><UpdatedPropertyDetails:updatedPropertyDetails xmlns:UpdatedPropertyDetails="http://www.zillow.com/static/xsd/UpdatedPropertyDetails.xsd" xsi:schemaLocation="http://www.zillow.com/static/xsd/UpdatedPropertyDetails.xsd https://www.zillowstatic.com/vstatic/80d5e73/static/xsd/UpdatedPropertyDetails.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><request><zpid>48749425</zpid></request><message><text>Request successfully processed</text><code>0</code></message><response><zpid>48749425</zpid><pageViewCount><currentMonth>1</currentMonth><total>1</total></pageViewCount><address><street>2114 Bigelow Ave N</street><zipcode>98109</zipcode><city>Seattle</city><state>WA</state><latitude>47.637934</latitude><longitude>-122.347936</longitude></address><links><homeDetails>https://www.zillow.com/homedetails/2114-Bigelow-Ave-N-Seattle-WA-98109/48749425_zpid/</homeDetails><photoGallery>https://www.zillow.com/homedetails/2114-Bigelow-Ave-N-Seattle-WA-98109/48749425_zpid/#image=lightbox%3Dtrue</photoGallery><homeInfo>https://www.zillow.com/homedetails/2114-Bigelow-Ave-N-Seattle-WA-98109/48749425_zpid/</homeInfo></links><images><count>1</count><image><url>https://photos.zillowstatic.com/p_d/ISxb3qa8s1cwx01000000000.jpg</url></image></images><editedFacts><useCode>SingleFamily</useCode><bedrooms>4</bedrooms><bathrooms>3.0</bathrooms><finishedSqFt>3470</finishedSqFt><lotSizeSqFt>4680</lotSizeSqFt><yearBuilt>1924</yearBuilt><yearUpdated>2003</yearUpdated><roof>Composition</roof><parkingType>Off-street</parkingType><heatingSources>Gas</heatingSources><rooms>Laundry room, Walk-in closet, Master bath, Office, Dining room, Family room, Breakfast nook</rooms></editedFacts><neighborhood>Queen Anne</neighborhood><schoolDistrict>Seattle</schoolDistrict><elementarySchool>John Hay</elementarySchool><middleSchool>McClure</middleSchool></response></UpdatedPropertyDetails:updatedPropertyDetails><!-- H:001  T:36ms  S:902  R:Thu Jan 09 17:36:49 PST 2020  B:5.0.63618-master.f1e988c~delivery_ready.0145e9f -->'

In [6]:
#import xml.etree.ElementTree as et
#import xml.dom.minidom as mdom
#(...)
#
#for i in range(10):
#    root = et.Element("main")
#    (...)
#
#    ugly_xml = et.tostring(root, 'utf-8', method='xml')
#    parsed_xml = mdom.parseString(ugly_xml)
#    nice_xml = parsed_xml.toprettyxml(indent=" " * 3)
#    with open('test.xml', 'a') as f:
#         f.write(nice_xml)

In [19]:
#convert XML to json

o = xmltodict.parse(response1)
json.dumps(o) # '{"e": {"a": ["text", "text"]}}'

'{"UpdatedPropertyDetails:updatedPropertyDetails": {"@xmlns:UpdatedPropertyDetails": "http://www.zillow.com/static/xsd/UpdatedPropertyDetails.xsd", "@xsi:schemaLocation": "http://www.zillow.com/static/xsd/UpdatedPropertyDetails.xsd https://www.zillowstatic.com/vstatic/80d5e73/static/xsd/UpdatedPropertyDetails.xsd", "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance", "request": {"zpid": "48749425"}, "message": {"text": "Request successfully processed", "code": "0"}, "response": {"zpid": "48749425", "pageViewCount": {"currentMonth": "1", "total": "1"}, "address": {"street": "2114 Bigelow Ave N", "zipcode": "98109", "city": "Seattle", "state": "WA", "latitude": "47.637934", "longitude": "-122.347936"}, "links": {"homeDetails": "https://www.zillow.com/homedetails/2114-Bigelow-Ave-N-Seattle-WA-98109/48749425_zpid/", "photoGallery": "https://www.zillow.com/homedetails/2114-Bigelow-Ave-N-Seattle-WA-98109/48749425_zpid/#image=lightbox%3Dtrue", "homeInfo": "https://www.zillow.com/homedetails/2114-Bigelow-Ave-N-Seattle-WA-98109/48749425_zpid/"}, "images": {"count": "1", "image": {"url": "https://photos.zillowstatic.com/p_d/ISxb3qa8s1cwx01000000000.jpg"}}, "editedFacts": {"useCode": "SingleFamily", "bedrooms": "4", "bathrooms": "3.0", "finishedSqFt": "3470", "lotSizeSqFt": "4680", "yearBuilt": "1924", "yearUpdated": "2003", "roof": "Composition", "parkingType": "Off-street", "heatingSources": "Gas", "rooms": "Laundry room, Walk-in closet, Master bath, Office, Dining room, Family room, Breakfast nook"}, "neighborhood": "Queen Anne", "schoolDistrict": "Seattle", "elementarySchool": "John Hay", "middleSchool": "McClure"}}}'

In [20]:
#convert json to Dataframe

from pandas.io.json import json_normalize
df = pd.DataFrame.from_dict(json_normalize(o), orient='columns')

df

,UpdatedPropertyDetails:updatedPropertyDetails.@xmlns:UpdatedPropertyDetails,UpdatedPropertyDetails:updatedPropertyDetails.@xsi:schemaLocation,UpdatedPropertyDetails:updatedPropertyDetails.@xmlns:xsi,UpdatedPropertyDetails:updatedPropertyDetails.request.zpid,UpdatedPropertyDetails:updatedPropertyDetails.message.text,UpdatedPropertyDetails:updatedPropertyDetails.message.code,UpdatedPropertyDetails:updatedPropertyDetails.response.zpid,UpdatedPropertyDetails:updatedPropertyDetails.response.pageViewCount.currentMonth,UpdatedPropertyDetails:updatedPropertyDetails.response.pageViewCount.total,UpdatedPropertyDetails:updatedPropertyDetails.response.address.street,...,UpdatedPropertyDetails:updatedPropertyDetails.response.editedFacts.yearBuilt,UpdatedPropertyDetails:updatedPropertyDetails.response.editedFacts.yearUpdated,UpdatedPropertyDetails:updatedPropertyDetails.response.editedFacts.roof,UpdatedPropertyDetails:updatedPropertyDetails.response.editedFacts.parkingType,UpdatedPropertyDetails:updatedPropertyDetails.response.editedFacts.heatingSources,UpdatedPropertyDetails:updatedPropertyDetails.response.editedFacts.rooms,UpdatedPropertyDetails:updatedPropertyDetails.response.neighborhood,UpdatedPropertyDetails:updatedPropertyDetails.response.schoolDistrict,UpdatedPropertyDetails:updatedPropertyDetails.response.elementarySchool,UpdatedPropertyDetails:updatedPropertyDetails.response.middleSchool
0,http://www.zillow.com/static/xsd/UpdatedProper...,http://www.zillow.com/static/xsd/UpdatedProper...,http://www.w3.org/2001/XMLSchema-instance,48749425,Request successfully processed,0,48749425,1,1,2114 Bigelow Ave N,...,1924,2003,Composition,Off-street,Gas,"Laundry room, Walk-in closet, Master bath, Off...",Queen Anne,Seattle,John Hay,McClure

In [18]:
#read XML data from file and convert into Dataframe

import pandas as pd
import xml.etree.ElementTree as ET
import io

def iter_docs(author):
    author_attr = author.attrib
    for doc in author.iter('document'):
        doc_dict = author_attr.copy()
        doc_dict.update(doc.attrib)
        doc_dict['data'] = doc.text
        yield doc_dict

xml_data = io.StringIO(u'''\
<author type="XXX" language="EN" gender="xx" feature="xx" web="foobar.com">
    <documents count="N">
        <document KEY="e95a9a6c790ecb95e46cf15bee517651" web="www.foo_bar_exmaple.com"><![CDATA[A large text with lots of strings and punctuations symbols [...]
]]>
        </document>
        <document KEY="bc360cfbafc39970587547215162f0db" web="www.foo_bar_exmaple.com"><![CDATA[A large text with lots of strings and punctuations symbols [...]
]]>
        </document>
        <document KEY="19e71144c50a8b9160b3f0955e906fce" web="www.foo_bar_exmaple.com"><![CDATA[A large text with lots of strings and punctuations symbols [...]
]]>
        </document>
        <document KEY="21d4af9021a174f61b884606c74d9e42" web="www.foo_bar_exmaple.com"><![CDATA[A large text with lots of strings and punctuations symbols [...]
]]>
        </document>
        <document KEY="28a45eb2460899763d709ca00ddbb665" web="www.foo_bar_exmaple.com"><![CDATA[A large text with lots of strings and punctuations symbols [...]
]]>
        </document>
        <document KEY="a0c0712a6a351f85d9f5757e9fff8946" web="www.foo_bar_exmaple.com"><![CDATA[A large text with lots of strings and punctuations symbols [...]
]]>
        </document>
        <document KEY="626726ba8d34d15d02b6d043c55fe691" web="www.foo_bar_exmaple.com"><![CDATA[A large text with lots of strings and punctuations symbols [...]
]]>
        </document>
        <document KEY="2cb473e0f102e2e4a40aa3006e412ae4" web="www.foo_bar_exmaple.com"><![CDATA[A large text with lots of strings and punctuations symbols [...] [...]
]]>
        </document>
    </documents>
</author>
''')

etree = ET.parse(xml_data) #create an ElementTree object 
doc_df = pd.DataFrame(list(iter_docs(etree.getroot())))
doc_df

,type,language,gender,feature,web,KEY,data
0,XXX,EN,xx,xx,www.foo_bar_exmaple.com,e95a9a6c790ecb95e46cf15bee517651,A large text with lots of strings and punctuat...
1,XXX,EN,xx,xx,www.foo_bar_exmaple.com,bc360cfbafc39970587547215162f0db,A large text with lots of strings and punctuat...
2,XXX,EN,xx,xx,www.foo_bar_exmaple.com,19e71144c50a8b9160b3f0955e906fce,A large text with lots of strings and punctuat...
3,XXX,EN,xx,xx,www.foo_bar_exmaple.com,21d4af9021a174f61b884606c74d9e42,A large text with lots of strings and punctuat...
4,XXX,EN,xx,xx,www.foo_bar_exmaple.com,28a45eb2460899763d709ca00ddbb665,A large text with lots of strings and punctuat...
5,XXX,EN,xx,xx,www.foo_bar_exmaple.com,a0c0712a6a351f85d9f5757e9fff8946,A large text with lots of strings and punctuat...
6,XXX,EN,xx,xx,www.foo_bar_exmaple.com,626726ba8d34d15d02b6d043c55fe691,A large text with lots of strings and punctuat...
7,XXX,EN,xx,xx,www.foo_bar_exmaple.com,2cb473e0f102e2e4a40aa3006e412ae4,A large text with lots of strings and punctuat...